POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "hello moto",
    "number": "9212921292"
}

###
GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/6a3421a456feed787db2e1bf

###
GET http://localhost:3001/api/persons/6a3421a456feed787db2e1b2

###
PUT http://localhost:3001/api/persons/6a3421a456feed787db2e1bf
